server:
  port: 8002

spring:
  application:
    name: cloud-zk-payment-service
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181